name: Build REx and run tests (Linux)

on:
  workflow_dispatch:
    inputs:
      gcc_version:
        description: "Specify g++ compiler version, e.g. g++-14 (leave blank for latest available)"
        required: false
        default: ""
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 4 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Select g++ Version
        run: |
          ls /usr/bin | grep ^g++- | sort -V
          
          if [ -n "${{ inputs.gcc_version }}" ]; then
            selected_gcc="${{ inputs.gcc_version }}"
            if ! ls /usr/bin/$selected_gcc &>/dev/null; then
              echo "❌ Error: Specified g++ version '$selected_gcc' does not exist!"
              exit 1
            fi
            echo "✅ Using requested g++ version: $selected_gcc"
          else
            selected_gcc=$(ls /usr/bin | grep ^g++- | sort -V | tail -n 1)
            echo "✅ Using latest g++ version: $selected_gcc"
          fi

          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/$selected_gcc 100
          g++ --version

      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Build C++ Project
        run: rex/scripts/build-gpp.sh

      - name: Add Executable to PATH
        run: echo "$(pwd)/rex/build/bin" >> $GITHUB_PATH

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Haxe
        run: |
          sudo apt-get update
          sudo apt-get install -y haxe

      - name: Install Scala
        run: |
          sudo apt-get update
          sudo apt-get install -y scala

      - name: Run Gradle Tests
        working-directory: rex-tests
        run: ./gradlew test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: test-results
          path: rex-tests/build/test-results/test

      - name: Upload JUnit HTML report
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: test-report
          path: rex-tests/build/reports/tests/test

      - name: Upload Test Summary
        if: always()
        run: cat rex-tests/build/test-results/test-summary.md >> $GITHUB_STEP_SUMMARY