name: Build REx and run tests (macOS)

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 4 * * 6'

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 45

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use GNU g++
        run: ln -sf $(brew --prefix)/bin/g++-14 /usr/local/bin/g++

      - name: Build C++ Project
        run: |
          g++ --version
          rex/scripts/build-gpp.sh

      - name: Add Executable to PATH
        run: echo "$(pwd)/rex/build/bin" >> $GITHUB_PATH

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Haxe
        run: brew install haxe

      - name: Install TypeScript
        run: npm install -g typescript

      - name: Install Scala
        run: brew install scala

      - name: Install Go
        run: brew install go

      - name: Run Gradle Tests
        working-directory: rex-tests
        run: ./gradlew test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: rex-tests/build/test-results/test

      - name: Upload JUnit HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: rex-tests/build/reports/tests/test

      - name: Upload Test Summary
        if: always()
        run: cat rex-tests/build/test-results/test-summary.md >> $GITHUB_STEP_SUMMARY